package vista;

import controlador.Controlador_Paciente;
import java.awt.Color;
import java.awt.Dimension;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Paciente;


public class InterRegistrarPaciente extends javax.swing.JInternalFrame {

    public InterRegistrarPaciente() {
        initComponents();
        this.setSize(new Dimension(400, 300));
        this.setTitle("Registrar Paciente");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        jDateChooser_fecha_nacimiento = new com.toedter.calendar.JDateChooser();
        txt_dni = new javax.swing.JTextField();
        txt_celular = new javax.swing.JTextField();
        jComboBox_sexo = new javax.swing.JComboBox<>();
        jButton_Guardar = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Registrar Paciente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("DNI:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Celular:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Sexo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 90, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Fecha de Nacimiento:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 160, -1));

        txt_nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 170, -1));

        txt_apellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 170, -1));

        jDateChooser_fecha_nacimiento.setDateFormatString("yyyy-MM-dd");
        jDateChooser_fecha_nacimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jDateChooser_fecha_nacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 170, -1));

        txt_dni.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 170, -1));

        txt_celular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_celular.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(txt_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 170, -1));

        jComboBox_sexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_sexo.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione sexo:", "F", "M" }));
        getContentPane().add(jComboBox_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 170, -1));

        jButton_Guardar.setBackground(new java.awt.Color(0, 204, 204));
        jButton_Guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Guardar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Guardar.setText("Guardar");
        jButton_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 90, 30));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarActionPerformed

        Paciente paciente = new Paciente();
        Controlador_Paciente controlPaciente = new Controlador_Paciente();

        if (!txt_nombre.getText().isEmpty() && !txt_apellido.getText().isEmpty() && !txt_dni.getText().isEmpty() && !txt_celular.getText().isEmpty()) {
            //JOptionPane.showMessageDialog(null, "Correcto");
            
            try {
            int dni = Integer.parseInt(txt_dni.getText().trim());
            int celular = Integer.parseInt(txt_celular.getText().trim());
            Date fechaNacimiento = jDateChooser_fecha_nacimiento.getDate();
            
            paciente.setNombre(txt_nombre.getText().trim());
            paciente.setApellido(txt_apellido.getText().trim());
            
            paciente.setFecha_nacimiento(fechaNacimiento);
            paciente.setDni(dni);
            paciente.setCelular(celular);
            
            String sexoSeleccionado = jComboBox_sexo.getSelectedItem().toString(); // Obtenemos el sexo seleccionado

            if ("F".equals(sexoSeleccionado)) {
                // Se seleccionó "Femenino"
                paciente.setSexo("F"); // Establece el sexo en "F"
            } else if ("M".equals(sexoSeleccionado)) {
                // Se seleccionó "Masculino"
                paciente.setSexo("M"); // Establece el sexo en "M"
            } 

                if (controlPaciente.guardar(paciente)) {
                    JOptionPane.showMessageDialog(null, "Registro Guardado");
                    txt_nombre.setBackground(Color.green);
                    txt_apellido.setBackground(Color.green);
                    jDateChooser_fecha_nacimiento.setBackground(Color.green);
                    txt_dni.setBackground(Color.green);
                    txt_celular.setBackground(Color.green);
                    jComboBox_sexo.setSelectedItem("Seleccione sexo:");
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Error al Guardar");
                }
                }catch (NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "El Paciente ya esta registrado en la Base de Datos.");
                    txt_nombre.setBackground(Color.white);
                    txt_apellido.setBackground(Color.white);
                    txt_dni.setBackground(Color.white);
                    jDateChooser_fecha_nacimiento.setBackground(Color.white);
                    txt_celular.setBackground(Color.white);
                    jComboBox_sexo.setSelectedItem("Seleccione sexo:");
                } 
        } else {
            JOptionPane.showMessageDialog(null, "Completa todos los campos");
            txt_nombre.setBackground(Color.red);
            txt_apellido.setBackground(Color.red);
            jDateChooser_fecha_nacimiento.setBackground(Color.red);
            txt_dni.setBackground(Color.red);
            txt_celular.setBackground(Color.red);
        }
        //metodo limpiar
        this.Limpiar();
    }//GEN-LAST:event_jButton_GuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Guardar;
    private javax.swing.JComboBox<String> jComboBox_sexo;
    private com.toedter.calendar.JDateChooser jDateChooser_fecha_nacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_celular;
    private javax.swing.JTextField txt_dni;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
     /**
     *
     * Metodo para limpiar campos
     */
    private void Limpiar() {
        txt_nombre.setText("");
        txt_apellido.setText("");
        jDateChooser_fecha_nacimiento.setDate(null);      
        txt_dni.setText("");
        txt_celular.setText("");

    }

}
