package vista;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import conexion.Conexion;
import controlador.Controlador_Cita;
import java.awt.Dimension;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import modelo.Cita;

/**
 *
 * @author ALDO
 */
public class InterRegistrarCita extends javax.swing.JInternalFrame {

    private int codPaciente;
    int obtenerCodDoctorCombo = 0;
    int obtenerCodServicio = 0;
    int obtenerCodArea = 0;
    

    /**
     * Creates new form InterRegistrarCita
     */
    public InterRegistrarCita() {
        initComponents();
        this.setSize(new Dimension(693, 467));
        this.setTitle("Registrar Cita");
        this.cargarComboDoctores();
        this.cargarComboServicio();
        this.cargarComboArea();
        this.CargarComboSexo();
        this.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_dni = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel_celular = new javax.swing.JLabel();
        txt_cliente_buscar = new javax.swing.JTextField();
        txt_celular = new javax.swing.JTextField();
        jButton_busca_cliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_servicio = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox_Doctor = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboBox_sexo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton_RegistrarCita = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jDateChooser_fecha_nacimiento = new com.toedter.calendar.JDateChooser();
        jDateChooser_fecha_cita1 = new com.toedter.calendar.JDateChooser();
        jComboBox_area = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Fecha de Nacimiento:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 150, -1));

        txt_dni.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txt_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 160, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("DNI:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 80, -1));

        txt_apellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 160, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Apellido:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 80, -1));

        txt_nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 160, -1));

        jLabel_celular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_celular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_celular.setText("Celular:");
        jPanel1.add(jLabel_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 70, -1));

        txt_cliente_buscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_cliente_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cliente_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cliente_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 380, -1));

        txt_celular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txt_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 170, 30));

        jButton_busca_cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_busca_cliente.setText("Buscar");
        jButton_busca_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_busca_clienteActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_busca_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 90, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Registrar Cita");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jComboBox_servicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_servicio.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox_servicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Servicio:", "Item 2", "Item 3", "Item 4" }));
        jComboBox_servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_servicioActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_servicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 170, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Servicio:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 80, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Doctor:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 80, 20));

        jComboBox_Doctor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_Doctor.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox_Doctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Doctor:", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_DoctorActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_Doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 170, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Fecha:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 80, -1));

        jComboBox_sexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_sexo.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Area:", "Item 2", "Item 3", "Item 4" }));
        jComboBox_sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_sexoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 170, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Área:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 40, 30));

        jButton_RegistrarCita.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_RegistrarCita.setText("Registrar");
        jButton_RegistrarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarCitaActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_RegistrarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 190, 60));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Nombre:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 80, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Sexo:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 80, 20));

        jDateChooser_fecha_nacimiento.setDateFormatString("yyyy-MM-dd");
        jDateChooser_fecha_nacimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jDateChooser_fecha_nacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 170, -1));

        jDateChooser_fecha_cita1.setDateFormatString("yyyy-MM-dd");
        jDateChooser_fecha_cita1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jDateChooser_fecha_cita1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 170, 30));

        jComboBox_area.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_area.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox_area.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Area:", "Item 2", "Item 3", "Item 4" }));
        jComboBox_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_areaActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 170, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondo-diseño.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_cliente_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cliente_buscarActionPerformed
        // TODO add your handling code here:
        String dniBuscado = txt_cliente_buscar.getText().trim();

        if (!dniBuscado.isEmpty()) {
            // Llamar a un método que busca al paciente por su DNI
            buscarPorDNI(dniBuscado);
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese un número de DNI válido para buscar.");
        }
    }//GEN-LAST:event_txt_cliente_buscarActionPerformed

    private void jButton_busca_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_busca_clienteActionPerformed

    }//GEN-LAST:event_jButton_busca_clienteActionPerformed

    private void jComboBox_servicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_servicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_servicioActionPerformed

    private void jComboBox_DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_DoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_DoctorActionPerformed

    private void jComboBox_sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_sexoActionPerformed

    private void jButton_RegistrarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarCitaActionPerformed
    Cita cita = new Cita();
    Controlador_Cita ctlCita = new Controlador_Cita();
    String servicio= "";
    String doctor= "";
    String area = "";
    servicio = jComboBox_servicio.getSelectedItem().toString().trim();
    doctor = jComboBox_Doctor.getSelectedItem().toString().trim();
    area = jComboBox_area.getSelectedItem().toString().trim();
    
    
    
    }//GEN-LAST:event_jButton_RegistrarCitaActionPerformed

    private void jComboBox_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_areaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_areaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_RegistrarCita;
    public javax.swing.JButton jButton_busca_cliente;
    public javax.swing.JComboBox<String> jComboBox_Doctor;
    public javax.swing.JComboBox<String> jComboBox_area;
    public javax.swing.JComboBox<String> jComboBox_servicio;
    public javax.swing.JComboBox<String> jComboBox_sexo;
    public com.toedter.calendar.JDateChooser jDateChooser_fecha_cita1;
    public com.toedter.calendar.JDateChooser jDateChooser_fecha_nacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_celular;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txt_apellido;
    public javax.swing.JTextField txt_celular;
    public javax.swing.JTextField txt_cliente_buscar;
    public javax.swing.JTextField txt_dni;
    public javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables

    private void cargarComboDoctores() {
        Connection cn = Conexion.conectar();
        String sql = "SELECT * FROM empleado"; // Puedes ajustar esto según tu modelo de datos
        Statement st;

        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox_Doctor.removeAllItems();
            jComboBox_Doctor.addItem("Seleccione clasificacion:");

            while (rs.next()) {
                jComboBox_Doctor.addItem(rs.getString("Nombre"));
            }

            cn.close();

        } catch (SQLException e) {
            System.out.println("¡Error al cargar doctores!");
        }
    }

    private int codDoctor() {

        String sql = "select * from empleado WHERE Nombre = '" + this.jComboBox_Doctor.getSelectedItem() + "'";
        Statement st;

        try {
            Connection cn = Conexion.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                obtenerCodDoctorCombo = rs.getInt("Codempleado");
            }

        } catch (SQLException e) {
            System.out.println("Error al obtener Cod Doctor");
        }

        return obtenerCodDoctorCombo;

    }

    private int codServicio() {

        String sql = "select * from clasificacion WHERE Nombre = '" + this.jComboBox_servicio.getSelectedItem() + "'";
        Statement st;

        try {
            Connection cn = Conexion.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                obtenerCodServicio = rs.getInt("CodClasificacion");
            }

        } catch (SQLException e) {
            System.out.println("Error al obtener Cod Servicio");
        }

        return obtenerCodServicio;

    }

    private void cargarComboServicio() {
        Connection cn = Conexion.conectar();
        String sql = "SELECT * FROM clasificacion"; // Puedes ajustar esto según tu modelo de datos
        Statement st;

        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox_servicio.removeAllItems();
            jComboBox_servicio.addItem("Seleccione clasificacion:");

            while (rs.next()) {
                jComboBox_servicio.addItem(rs.getString("Nombre"));
            }

            cn.close();

        } catch (SQLException e) {
            System.out.println("¡Error al cargar servicio!");
        }
    }
    
    private int area() {

        String sql = "select * from areaatencion WHERE nombre = '" + this.jComboBox_area.getSelectedItem() + "'";
        Statement st;

        try {
            Connection cn = Conexion.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                obtenerCodArea= rs.getInt("CodArea");
            }

        } catch (SQLException e) {
            System.out.println("Error al obtener Cod Area");
        }

        return obtenerCodArea;

    }
    
    private void cargarComboArea() {
        Connection cn = Conexion.conectar();
        String sql = "SELECT * FROM areaatencion"; // Puedes ajustar esto según tu modelo de datos
        Statement st;

        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox_area.removeAllItems();
            jComboBox_area.addItem("Seleccione clasificacion:");

            while (rs.next()) {
                jComboBox_area.addItem(rs.getString("Nombre"));
            }

            cn.close();

        } catch (SQLException e) {
            System.out.println("¡Error al cargar servicio!");
        }
    }
    private void CargarComboSexo() {
        jComboBox_sexo.removeAllItems();
        jComboBox_sexo.addItem("Seleccione Género:");
        jComboBox_sexo.addItem("F");
        jComboBox_sexo.addItem("M");

    }
    
    private void buscarPorDNI(String dniBuscado) {
        if (!dniBuscado.isEmpty()) {
            try {
                int dni = Integer.parseInt(dniBuscado);
                Controlador_Cita controlCita = new Controlador_Cita();
                Cita cita = controlCita.buscarPorDNI(dni);

                if (cita != null) {
                    txt_nombre.setText(cita.getNombre());
                    txt_apellido.setText(cita.getApellido());
                    jDateChooser_fecha_nacimiento.setDate(cita.getFecha_nacimiento());
                    txt_dni.setText(String.valueOf(cita.getDni()));
                    txt_celular.setText(String.valueOf(cita.getCelular()));
                    jComboBox_sexo.setSelectedItem(cita.getSexo());
                    codPaciente =cita.getCodPaciente();
                } else {
                    JOptionPane.showMessageDialog(null, "Paciente no encontrado para el DNI ingresado.");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese un número de DNI válido para buscar.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese un número de DNI válido para buscar.");
        }
    }
    
    private void Limpiar() {
        txt_nombre.setText("");
        txt_apellido.setText("");
        jDateChooser_fecha_nacimiento.setDate(null);
        txt_dni.setText("");
        txt_celular.setText("");
        jComboBox_sexo.setSelectedItem("Seleccione sexo:");
    }

}
