package vista;

import conexion.Conexion;
import controlador.Controlador_Empleado;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import modelo.Empleado;


public class InterRegistrarEmpleado extends javax.swing.JInternalFrame {

    int obtenerCodEspecialidadCombo = 0;

    public InterRegistrarEmpleado() {
        initComponents();
        this.setSize(new Dimension(400, 333));
        this.setTitle("Registrar Empleado");

        this.CargarComboEspecialidades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_dni = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        txt_celular = new javax.swing.JTextField();
        jComboBox_especialidad = new javax.swing.JComboBox<>();
        jButton_Guardar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel_wallpaper = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Registrar Empleado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("DNI :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 160, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Correo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Celular:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 90, -1));

        txt_nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 170, -1));

        txt_apellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 170, -1));

        txt_dni.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 170, -1));

        txt_correo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 170, -1));

        txt_celular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 170, -1));

        jComboBox_especialidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_especialidad.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox_especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione especialidad:", "Item 2", "Item 3", "Item 4" }));
        jComboBox_especialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_especialidadActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 170, -1));

        jButton_Guardar.setBackground(new java.awt.Color(0, 204, 204));
        jButton_Guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Guardar.setText("Guardar");
        jButton_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 90, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Especialidad:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 90, -1));

        jLabel_wallpaper.setBackground(new java.awt.Color(153, 153, 255));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 410, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarActionPerformed

        Empleado empleado = new Empleado();
        Controlador_Empleado controlEmpleado = new Controlador_Empleado();
        
        String especialidad = "";
        
        especialidad = jComboBox_especialidad.getSelectedItem().toString().trim();

        //validar campos
        if (txt_nombre.getText().equals("") || txt_apellido.getText().equals("") || txt_dni.getText().equals("") || txt_correo.getText().equals("") || txt_celular.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
            txt_nombre.setBackground(Color.red);
            txt_apellido.setBackground(Color.red);
            txt_dni.setBackground(Color.red);
            txt_correo.setBackground(Color.red);
            txt_celular.setBackground(Color.red);
            
        } else {
            //consulta para ver si el empleado ya existe
            if (!controlEmpleado.existeEmpleado(txt_dni.getText().trim())){
                if (especialidad.equalsIgnoreCase("Seleccione especialidad:")) {
                    JOptionPane.showMessageDialog(null, "Seleccione especialidad");
                } else {
                    try {
                        empleado.setNombre(txt_nombre.getText().trim());
                        empleado.setApellido(txt_apellido.getText().trim());
                        empleado.setDni(Integer.parseInt(txt_dni.getText().trim()));
                        empleado.setCorreo(txt_correo.getText().trim());
                        empleado.setCelular(Integer.parseInt(txt_celular.getText().trim()));
                        
                        // Id de la especialidad
                        this.CodEspecialidad();
                        empleado.setCodEspecialidad(obtenerCodEspecialidadCombo);

                        if (controlEmpleado.guardar(empleado)) {
                            JOptionPane.showMessageDialog(null, "Registro Guardado");
                            txt_nombre.setBackground(Color.green);
                            txt_apellido.setBackground(Color.green);
                            txt_dni.setBackground(Color.green);
                            txt_correo.setBackground(Color.green);
                            txt_celular.setBackground(Color.green);

                            this.CargarComboEspecialidades();
                            this.Limpiar();
                        } else {
                            JOptionPane.showMessageDialog(null, "Error al Guardar");
                        }

                    } catch (HeadlessException | NumberFormatException e) {
                        System.out.println("Error en: " + e);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "El empleado ya existe en la Base de Datos");
            }
        }
        
        
    }//GEN-LAST:event_jButton_GuardarActionPerformed

    private void jComboBox_especialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_especialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_especialidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Guardar;
    private javax.swing.JComboBox<String> jComboBox_especialidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_celular;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_dni;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables

    private void Limpiar() {
        
        txt_nombre.setText("");
        txt_apellido.setText("");
        txt_dni.setText("");
        txt_correo.setText("");
        txt_celular.setText("");

    }    
    
    
    //Metodo para Especialidades
    
    private void CargarComboEspecialidades() {
        Connection cn = Conexion.conectar();
        String sql = "select Nombre from Especialidad";
        Statement st;

        try {

            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox_especialidad.removeAllItems();
            jComboBox_especialidad.addItem("Seleccione Especialidad:");
            while (rs.next()) {
                jComboBox_especialidad.addItem(rs.getString("Nombre"));
            }
            cn.close();

        } catch (SQLException e) {
            System.out.println("Error al cargar especialidades");
        }
        
    }

    private int CodEspecialidad() {
        String sql = "select * from Especialidad where Nombre = '" + this.jComboBox_especialidad.getSelectedItem() + "'";
        Statement st;
        try {
            Connection cn = Conexion.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                obtenerCodEspecialidadCombo = rs.getInt("CodEspecialidad");
            }
        } catch (SQLException e) {
            System.out.println("Error al obener Cod Especialidad");
        }
        return obtenerCodEspecialidadCombo;
    }
        
}

